[package]
name = "twitchrs"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.18"
crossterm = "0.23"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
